version: '3.9'
services:
  app:
    container_name: app
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload --reload-dir /app